/**
 * Copyright © 2010 Nokia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.googlecode.jsonschema2pojo.rules;

import java.util.Date;

import org.codehaus.jackson.JsonNode;

import com.sun.codemodel.JPackage;
import com.sun.codemodel.JType;

/**
 * Applies the "format" schema rule.
 * 
 * @see <a
 *      href="http://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23">http://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23</a>
 */
public class FormatRule implements SchemaRule<JPackage, JType> {
    
    /**
     * Applies this schema rule to take the required code generation steps.
     * <p>
     * This rule maps format values to Java types:
     * <ul>
     *     <li>"format":"date-time" => {@link Date}
     *     <li>"format":"date" => {@link String}
     *     <li>"format":"time" => {@link String}
     *     <li>"format":"utc-millisec" => <code>long</code>
     *     <li>"format":"regex" => {@link String}
     *     <li>"format":"color" => {@link String}
     *     <li>"format":"style" => {@link String}
     *     <li>"format":"phone" => {@link String}
     *     <li>"format":"uri" => {@link String}
     *     <li>"format":"email" => {@link String}
     *     <li>"format":"ip-address" => {@link String}
     *     <li>"format":"ipv6" => {@link String}
     *     <li>"format":"host-name" => {@link String}
     *     <li>other => {@link String}
     * </ul> 
     * 
     * @param nodeName
     *            the name of the node to which this format is applied
     * @param node
     *            the format node
     * @param generatableType
     *            the package into which any types generated by this rule should
     *            be added
     * @return the Java type that is appropriate for the format value 
     */
    @Override
    public JType apply(String nodeName, JsonNode node, JPackage generatableType) {
        
        if (node.getTextValue().equals("date-time")) {
            return generatableType.owner().ref(Date.class);
            
        } else if (node.getTextValue().equals("utc-millisec")) {
            return generatableType.owner().LONG;
            
        } else {
            return generatableType.owner().ref(String.class);
        }
        
    }
    
}
