/**
 * Copyright © 2010-2020 Nokia
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jsonschema2pojo.integration.classpath;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A pre-compiled enum that simulates the pattern generated by jsonschema2pojo.
 * Used by integration tests to verify that default values are correctly applied
 * when an enum type already exists on the classpath.
 *
 * @see <a href="https://github.com/joelittlejohn/jsonschema2pojo/issues/926">issue #926</a>
 */
public enum ExistingClasspathEnum {

    ALPHA("alpha"),
    BETA("beta"),
    GAMMA("gamma");

    private final String value;
    private static final Map<String, ExistingClasspathEnum> CONSTANTS = new HashMap<>();

    static {
        for (ExistingClasspathEnum c : values()) {
            CONSTANTS.put(c.value, c);
        }
    }

    ExistingClasspathEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ExistingClasspathEnum fromValue(String value) {
        ExistingClasspathEnum constant = CONSTANTS.get(value);
        if (constant == null) {
            throw new IllegalArgumentException(value);
        }
        return constant;
    }

    @Override
    public String toString() {
        return this.value;
    }
}