name: Android Sample

on: [pull_request]

jobs:
  buildTest:
    name: Build JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jsonschema2pojo-gradle-plugin/example/android
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Build project
        run: ./gradlew assembleDebug
