---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        java_version: [8, 11, 17, 21]
      max-parallel: 4
    name: Test JDK ${{ matrix.java_version }}
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}
      - name: Verify with Maven
        run: ./mvnw verify -B
      - name: Verify jsonschema2pojo-gradle-plugin integration tests
        run: |
          ./mvnw -U -B install -DskipTests -Dmaven.javadoc.skip -Dmaven.site.skip -pl jsonschema2pojo-gradle-plugin -am
          ./mvnw -U -B install -pl jsonschema2pojo-gradle-plugin
